### ISSUE TITLE
Performance of st_nn when parallel > 1

### ISSUE THREAD

**Issue by mem48** [michaeldorman/nngeo#17] opened 2020-10-05 15:28 UTC
Hi, I've been using `st_nn` for `sf` points and I noticed that it is much slower using parallel processing.

I had a look at the source code and I think the way you structure the function is causing a lot of unnecessary copying of data.

For example with 10,000 points I get:

Single Core:
```
> system.time(r1 <- nngeo::st_nn(x, y, k = 50, parallel = 1))
   user  system elapsed 
  23.33    0.41   24.25 
```
 4 Core: Much slower
```
> system.time(r1 <- nngeo::st_nn(x, y, k = 50, parallel = 4))
   user  system elapsed 
   6.34    0.27   65.10
```

Tweaked code: Better but not 4x faster

```
system.time({
  cl = parallel::makeCluster(4)
  x_split = split(x, 1:4)
  parallel::clusterExport(
    cl = cl,
    varlist = c("y"),
    envir = environment()
  )
  result = parallel::parLapply(
    cl,
    x_split,
    function(i) nngeo:::.st_nn_pnt_proj(i, y, k = 50, maxdist = Inf, progress = FALSE)
  )
  parallel::stopCluster(cl)
  ids = lapply(result, `[[`, 1)
  ids = unlist(ids, recursive = FALSE, use.names = FALSE)
   r2 = ids
})
   user  system elapsed 
   0.55    0.06   10.86

> identical(r1, r2)
[1] TRUE

```

This might be a windows only issue as the way parallelisation works on Linux is very different.

**Comment by michaeldorman** [comment] 2020-10-06 22:09
Thanks, this is very interesting. I don't know how this can happen, and couldn't reproduce the issue yet. 

-----

Here is a test on Linux:


``` r
library(nngeo)
```

    ## Loading required package: sf

    ## Linking to GEOS 3.8.1, GDAL 3.1.3, PROJ 7.1.1

``` r
# Sample layer
n = 10000 
x = data.frame(
  lon = (runif(n) * 2 - 1) * 70, 
  lat = (runif(n) * 2 - 1) * 70 
) 
x = st_as_sf(x, coords = c("lon", "lat"), crs = 4326)

# Single thread
start = Sys.time()
result1 = st_nn(x, x, k = 50, progress = FALSE) 
```

    ## lon-lat points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 2.913562 mins

``` r
# Parallel
start = Sys.time() 
result2 = st_nn(x, x, k = 50, parallel = 2) 
```

    ## lon-lat points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 1.796661 mins

``` r
# Compare results
all.equal(result1, result2)
```

    ## [1] TRUE

-----

and the same test on Windows:


``` r
library(nngeo)
```

    ## Loading required package: sf

    ## Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

``` r
# Sample layer
n = 10000 
x = data.frame(
  lon = (runif(n) * 2 - 1) * 70, 
  lat = (runif(n) * 2 - 1) * 70 
) 
x = st_as_sf(x, coords = c("lon", "lat"), crs = 4326)

# Single thread
start = Sys.time()
result1 = st_nn(x, x, k = 50, progress = FALSE) 
```

    ## lon-lat points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 4.693713 mins

``` r
# Single thread
start = Sys.time() 
result2 = st_nn(x, x, k = 50, parallel = 2) 
```

    ## lon-lat points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 2.694491 mins

``` r
# Compare results
all.equal(result1, result2)
```

    ## [1] TRUE

-----

In both cases the parallel method is ~2 times faster than the single-thread method. However I'm using a virtual Windows system (through VirtualBox). Once I have access to a computer with an ordinary Windows installation will try to re-check this.

**Comment by mem48** [comment] 2020-10-07 10:40
I used projected points so that may have made a difference? Running your example I got very similar results.

But changing just the crs to 27700 I get:

```
Time difference of 24.18745 secs
Time difference of 1.899048 mins
```

**Comment by mem48** [comment] 2020-10-07 10:44
I think the main problems is here:

```
split(x, 1:length(x))
```
In parLapply you should split to the number of workers, then one part is sent to each worker which minimises the data copying between workers.

**Comment by michaeldorman** [comment] 2020-10-07 12:58
Thanks for looking into this, you are right! I see the problem now, and I think it's not related to Windows because it takes place in Linux too. Will look into it and get back to you.


``` r
library(nngeo)
```

    ## Loading required package: sf

    ## Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

``` r
# Sample layer
n = 10000 
x = data.frame(
  lon = (runif(n) * 2 - 1) * 70, 
  lat = (runif(n) * 2 - 1) * 70 
) 
x = st_as_sf(x, coords = c("lon", "lat"), crs = 27700)

# Single thread
start = Sys.time()
result1 = st_nn(x, x, k = 50, progress = FALSE) 
```

    ## projected points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 7.106086 secs

``` r
# Parallel
start = Sys.time() 
result2 = st_nn(x, x, k = 50, parallel = 2) 
```

    ## projected points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 53.96069 secs

``` r
# Compare results
all.equal(result1, result2)
```

    ## [1] TRUE

**Comment by michaeldorman** [comment] 2020-10-07 14:06
The problem seems to be that when processing projected points there is not benefit in parallel processing, since the underlying function `RANN::nn2` is already highly optimized (it is somehow indexing all points together, rather than one-by-one). Perhaps the benefit can be revealed when the number of points is very large, when splitting to parts as number of workers like you suggested. Meanwhile I disabled the option of `parallel>0` with projected points to avoid the unnecessary delay. 

Will be interesting if you can please elaborate, in your use case, how many projected points are you working with? I wonder if there is a practical use for parallel processing on top of `RANN::nn2`.

Thanks!

**Comment by mem48** [comment] 2020-10-07 15:24
Interesting, I've also been using `nabor::knn` which is supposed to be a faster drop-in replacement for `RANN::nn2`.

So my specific use case is I'm matching car crash data (points) to the roads (lines) and junctions (points). The idea is to work out where are the most dangerous roads and junctions.  

The code to do this is [here](https://github.com/saferactive/saferactive/blob/master/code/osm_cleaning.R) and [here](https://github.com/saferactive/saferactive/blob/master/code/osm_cleaning_functions.R) you might also be interested in this GitHub [issue](https://github.com/saferactive/saferactive/issues/36) where we are discussing progress and includes some plots.

You can get UK car crash data with the `stats19` package, I'm using the last 10 years of data, so hundreds of thousands of crashes, hence the interest in parallel processing and optimising for speed.

At the moment I'm not using the `nngeo` package in my code, due to the above issues. But you should be able to transfer the principles into your package.

**Comment by michaeldorman** [comment] 2020-10-08 20:33
Thanks for those links, very interesting discussion and functions!

Also thanks for pointing out `nabor`, I wasn't aware of it. Now replaced `RANN` with `nabor`. While at it, also noticed some unnecessary code for converting units of measurement to meters when they already are. So `st_nn` for projected points should be noticeably faster now. For example, the code which took ~7 seconds in the last comment now takes ~0.5 second:


``` r
library(nngeo)
```

    ## Loading required package: sf

    ## Linking to GEOS 3.8.1, GDAL 3.1.3, PROJ 7.1.1

``` r
# Sample layer
n = 10000
x = data.frame(
  lon = (runif(n) * 2 - 1) * 70, 
  lat = (runif(n) * 2 - 1) * 70 
) 
x = st_as_sf(x, coords = c("lon", "lat"), crs = 27700)

# Single thread
start = Sys.time()
result = st_nn(x, x, k = 50, progress = FALSE)
```

    ## projected points

``` r
end = Sys.time() 
end - start
```

    ## Time difference of 0.4245496 secs

**Closed as completed** 2020-12-02 20:21 UTC
